PROJECT_NAME = "AnalyticaHouseCase"
PROJECT_BUNDLE = "com.analyticahouse"
DEVELOPMENT_PROJECT_BUNDLE = "com.analyticahousedev"
PROJECT_SCHEME = "AnalyticaHouseCase"

default_platform(:ios)

platform :ios do

desc "Sign Code"
lane :sign do
      # get_certificates           # invokes cert
      get_provisioning_profile   # invokes sigh

end 


lane :increment_version do
   latestBuildNumber = get_build_number(xcodeproj: "AnalyticalHouseCase.xcodeproj")
   newBuildNumber = ((latestBuildNumber.is_a? String) ? latestBuildNumber.to_i : latestBuildNumber) + 0.1
   increment_build_number(build_number: newBuildNumber)
end

# development build
lane :build_test do |values|
  build("DevelopmentRelease", "#{DEVELOPMENT_PROJECT_BUNDLE}")
 end

# production build
 lane :build_production do |values|
  build("ProductionRelease", "#{PROJECT_BUNDLE}")
 end

def build(configuration, project_bundle)
  gym( scheme: "#{PROJECT_SCHEME}",
  configuration: configuration,
  clean: true,
  export_options: {
      export_xcargs: "-allowProvisioningUpdates",
      
    }
  )
end





end